name: qc
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - opencv
  - pytorch=2.3.0
  - torchvision=0.18.0
  - torchaudio=2.3.0
  - sentence-transformers
  - transformers
  - jupyterlab
  - ipywidgets
  - typing_extensions
  - matplotlib-base
  - tk
  - pyyaml
  - setuptools
  - wheel
  - ca-certificates
  - certifi
  - openssl
  - zlib
  - libpng
  - pillow
  - ffmpeg
  - xz
  - lz4-c
  - pip:
      - openai
      - langchain
      - langchain-core
      - langchain-community
      - langchain-huggingface
      - langsmith
      - huggingface-hub
      - sentence-transformers
      - tqdm
      - ipython
      - jupyter-core
      - nbformat
      - joblib
      - fsspec
      - typing-inspect
      - typing-inspection
      - regex
      - requests
      - requests-toolbelt
      - aiohttp
      - rich
      - soupsieve
      - beautifulsoup4
      - flask
      - dash
      - plotly
      - markdownify
      - open3d
      - orjson
      - faiss-cpu
      - scikit-learn
      - python-dotenv
      - python-lzf
      - pywin32
      - zstandard
      - jsonschema
      - jsonpatch
      - jsonpointer
      - decorator
      - click
      - pygments
      - pure-eval
      - traitlets
      - prompt-toolkit
      - platformdirs
      - werkzeug
      - tornado
      - greenlet
      - sqlalchemy
      - tenacity
      - dash
      - jinja2
      - importlib-metadata
      - lxml
      - markdown-it-py
      - mdurl
      - aiohappyeyeballs
      - aiosignal
      - async-timeout
      - blinker
      - nest-asyncio
      - comm
      - jupyterlab-widgets
      - widgetsnbextension
      - unicodedata2
